### ISSUE TITLE
Scaning from txt file with hostnames list?

### ISSUE THREAD

**Issue by ghost** [franccesco/getaltname#7] opened 2019-01-06 12:00 UTC
Can you add this pls :3

**Comment by franccesco** [comment] 2019-12-13 17:21
@BBerastegui That's an option that I have in mind, I might also introduce an option to scan a list of domains on a txt file (ip's or hostnames only), I'm currently developing the next version because the current one is very hard to maintain and develop. I'll reopen the issue and close it once the feature is out.

**Comment by BBerastegui** [comment] 2019-12-14 19:34
IMHO, this tool should stick to what it currently does (and does really good), and such functionality should not be scanning for https services (as there are other tools that do that atm).

If someone wants that, they should use nmap or other tool built for such thing specifically (such as httprobe that I linked it before). My two cents.

I forked the project and I was going to add that option by myself, but good to hear that you are already on it. I'll wait here then!

**Comment by franccesco** [comment] 2019-12-14 19:57
> IMHO, this tool should stick to what it currently does (and does really good), and such functionality should not be scanning for https services (as there are other tools that do that atm).

That's correct, I did a bad job at explaining myself there, what I meant is that the tool will go through a list of confirmed https services and then try to extract the subdomain names directly, it will not _scan_ them. The feature will be out in a couple of days.

**Comment by franccesco** [comment] 2020-01-06 00:20
@BBerastegui 

The feature is out now, you should be able to run an update and then check if you can use it with no problems. You can pass a list of host[:port] instead of a domain name:

```
$ gsan scan text_file.txt
```

It should do the trick, let me know if it works correctly.

**Comment by BBerastegui** [comment] 2020-01-16 11:15
I've just tried with `host:port` format and it works perfectly.

If you accept one suggestion more, I would also handle the case where the file contains: `https://host:port` too, even if it's just by discarding the `https?://` part :D

Cheers and thanks again!

**Comment by franccesco** [comment] 2020-10-08 03:43
Sorry for commenting on this so late. For now I think a combination of `host:port` is enough. Including `https://` would be redundant because we're always making an HTTPS connection.

**Closed by franccesco** 2020-10-08 03:43 UTC
